### ISSUE TITLE
Hey hey

### ISSUE THREAD

**Issue by ghost** [gjtorikian/testing#111]
@gjtorikian

**Comment by not-gjtorikian** [comment]
@gjtorikian did you get this?

**Comment by gjtorikian** [comment]
@gjtorikian Yes I got it.

**Comment by gjtorikian** [comment]
@gjtorikian I got these, thanks.

**Comment by gjtorikian** [comment]
@gjtorikian I got them!

**Comment by gjtorikian** [comment]
@gjtorikian Thanks, I got it.

**Comment by gjtorikian** [comment]
@gjtorikian I said thank you, I got it!

**Comment by not-gjtorikian** [comment]
@gjtorikian That's great!
